<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Protego · Zimbabwe privacy operations</title>
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body class="min-h-screen bg-[#0e1b23] text-white">
    <header class="absolute inset-x-0 top-0 z-10"><div class="mx-auto flex max-w-7xl items-center justify-between px-6 py-6 lg:px-10"><a href="{{ route('home') }}" class="inline-flex items-center gap-3"><span class="grid size-10 place-items-center bg-cyan-300 font-black text-[#0e1b23]">P</span><span><strong class="block text-sm">Protego</strong><small class="block text-[10px] uppercase tracking-[0.2em] text-slate-400">Zimbabwe privacy ops</small></span></a><nav class="flex items-center gap-3"><a href="{{ route('login') }}" class="px-4 py-2 text-sm font-bold text-slate-300 hover:text-white">Sign in</a><a href="{{ route('register') }}" class="bg-cyan-300 px-4 py-2 text-sm font-bold text-[#0e1b23] hover:bg-cyan-200">Create workspace</a></nav></div></header>
    <main>
        <section class="relative isolate overflow-hidden px-6 pb-24 pt-40 lg:px-10 lg:pb-36 lg:pt-52"><div class="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_72%_35%,rgba(45,212,191,0.16),transparent_32%),linear-gradient(125deg,#0e1b23_10%,#12323a_100%)]"></div><div class="absolute right-[12%] top-40 -z-10 hidden size-[28rem] rounded-full border border-cyan-300/10 lg:block"></div><div class="mx-auto grid max-w-7xl gap-16 lg:grid-cols-[1fr_0.7fr] lg:items-end"><div><p class="mb-6 text-sm font-bold uppercase tracking-[0.25em] text-cyan-300">Data protection, operationalised</p><h1 class="max-w-3xl text-5xl font-bold leading-[0.98] tracking-[-0.06em] sm:text-7xl">Make compliance feel manageable.</h1><p class="mt-8 max-w-xl text-lg leading-8 text-slate-300">Protego gives Zimbabwean organisations a clear place to prepare POTRAZ submissions, maintain their processing register, and respond to incidents before the clock runs out.</p><div class="mt-10 flex flex-wrap gap-3"><a href="{{ route('register') }}" class="bg-cyan-300 px-6 py-4 text-sm font-bold text-[#0e1b23] hover:bg-cyan-200">Build your workspace <span aria-hidden="true">↗</span></a><a href="{{ route('login') }}" class="border border-slate-600 px-6 py-4 text-sm font-bold text-white hover:border-slate-400">Sign in</a></div></div><div class="border-l border-cyan-300/30 pl-6 lg:mb-2"><p class="text-xs font-bold uppercase tracking-[0.2em] text-slate-500">One operating rhythm</p><div class="mt-6 grid gap-5"><div><p class="text-2xl font-bold">DP1</p><p class="mt-1 text-sm text-slate-400">Licensing and renewal readiness</p></div><div><p class="text-2xl font-bold">DP2</p><p class="mt-1 text-sm text-slate-400">A defensible DPO appointment record</p></div><div><p class="text-2xl font-bold">DP3</p><p class="mt-1 text-sm text-slate-400">A visible 24-hour response clock</p></div></div></div></div></section>
        <section class="bg-[#f4f7f8] px-6 py-20 text-slate-900 lg:px-10"><div class="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[0.75fr_1.25fr] lg:items-start"><div><p class="text-xs font-bold uppercase tracking-[0.2em] text-cyan-700">Designed for the work</p><h2 class="mt-4 text-3xl font-bold tracking-tight lg:text-4xl">The evidence is already in your operations.</h2></div><div class="grid gap-8 sm:grid-cols-3"><div><p class="text-3xl font-bold text-cyan-800">01</p><h3 class="mt-4 font-bold">Capture once</h3><p class="mt-2 text-sm leading-6 text-slate-500">Structure your entity, processing, and safeguards details in one consistent record.</p></div><div><p class="text-3xl font-bold text-cyan-800">02</p><h3 class="mt-4 font-bold">Stay current</h3><p class="mt-2 text-sm leading-6 text-slate-500">Keep DPO appointments and your ROPA register ready for review.</p></div><div><p class="text-3xl font-bold text-cyan-800">03</p><h3 class="mt-4 font-bold">Respond clearly</h3><p class="mt-2 text-sm leading-6 text-slate-500">Log incidents early and preserve the facts needed for a DP3 notice.</p></div></div></div></section>
    </main>
</body>
</html>
