@extends('layouts.app')

@section('content')
<x-page-heading eyebrow="Reports" title="Compliance reports" description="Status, overdue work, upcoming obligations, owner performance and category score." />
<form method="GET" class="surface mb-6 grid gap-3 p-4 sm:grid-cols-[1fr_1fr_auto]"><input type="date" name="from" value="{{ $from }}" class="form-control"><input type="date" name="to" value="{{ $to }}" class="form-control"><button class="button-secondary">Apply</button></form>
<section class="grid gap-4 sm:grid-cols-3"><div class="surface p-5"><span class="text-xs font-bold uppercase text-slate-500">Score</span><p class="mt-3 text-3xl font-bold">{{ $score }}%</p></div><div class="surface p-5"><span class="text-xs font-bold uppercase text-slate-500">Due</span><p class="mt-3 text-3xl font-bold">{{ $dueCount }}</p></div><div class="surface p-5"><span class="text-xs font-bold uppercase text-slate-500">Completed on time</span><p class="mt-3 text-3xl font-bold">{{ $completedOnTime }}</p></div></section>
<section class="mt-6 grid gap-6 xl:grid-cols-2">
    <div class="surface p-5"><h2 class="font-bold">Overdue obligations</h2><div class="mt-4 grid gap-2">@forelse($overdue as $item)<a href="{{ route('compliance.calendar.show', $item) }}" class="border border-slate-200 p-3 text-sm">{{ $item->title }}<span class="block text-xs text-slate-500">{{ $item->due_at->format('d M Y') }} · {{ $item->assignedUser?->name ?? 'Unassigned' }}</span></a>@empty<p class="text-sm text-slate-500">No overdue obligations.</p>@endforelse</div></div>
    <div class="surface p-5"><h2 class="font-bold">Upcoming obligations</h2><div class="mt-4 grid gap-2">@forelse($upcoming as $item)<a href="{{ route('compliance.calendar.show', $item) }}" class="border border-slate-200 p-3 text-sm">{{ $item->title }}<span class="block text-xs text-slate-500">{{ $item->due_at->format('d M Y') }} · {{ $item->assignedUser?->name ?? 'Unassigned' }}</span></a>@empty<p class="text-sm text-slate-500">No upcoming obligations in the next 30 days.</p>@endforelse</div></div>
    <div class="surface p-5"><h2 class="font-bold">Score by category and status</h2><div class="mt-4 grid gap-2">@foreach($byCategory as $row)<div class="flex justify-between border border-slate-200 px-3 py-2 text-sm"><span>{{ $row->category }} · {{ str($row->status)->headline() }}</span><strong>{{ $row->total }}</strong></div>@endforeach</div></div>
    <div class="surface p-5"><h2 class="font-bold">Owner performance</h2><div class="mt-4 grid gap-2">@foreach($ownerPerformance as $owner => $items)<div class="flex justify-between border border-slate-200 px-3 py-2 text-sm"><span>{{ $owner }}</span><strong>{{ $items->where('status', 'completed')->count() }}/{{ $items->count() }}</strong></div>@endforeach</div></div>
</section>
@endsection
