@extends('layouts.app')
@section('content')
<x-page-heading eyebrow="DP2 · New appointment" title="Record a DPO appointment" description="Capture the controller and appointed officer details required by the official POTRAZ DP2 notification form." />
<form method="POST" action="{{ route('compliance.dp2.store') }}" class="surface grid gap-8 p-6 lg:grid-cols-2 lg:p-8">
    @csrf
    <div class="grid gap-5 lg:col-span-2"><h2 class="border-b border-slate-200 pb-3 font-bold">1. Client information</h2><div class="grid gap-5 md:grid-cols-2"><x-field name="controller_name" label="Name of data controller" required /><x-field name="controller_license_number" label="Data controller licence number" required /><x-textarea name="controller_physical_address" label="Physical address" required /><x-textarea name="controller_postal_address" label="Postal address" required /><x-field name="controller_telephone" label="Telephone / cell number" required /><x-field name="controller_fax" label="Fax number" /><x-field name="controller_email" label="Controller email" type="email" required /><x-textarea name="business_scope" label="Scope of business operations" required /></div></div>
    <div class="grid gap-5 lg:col-span-2"><h2 class="border-b border-slate-200 pb-3 font-bold">2. Appointed data protection officer</h2><div class="grid gap-5 md:grid-cols-2"><x-field name="full_name" label="Name of appointed DPO" required /><x-field name="dpo_registration_number" label="DPO registration number" /><x-field name="official_email" label="Email of DPO" type="email" required /><x-field name="official_phone" label="DPO telephone number" required /><x-field name="dpo_mobile" label="DPO mobile number" required /><x-textarea name="dpo_address" label="Address of DPO" required /><x-textarea name="qualifications" label="Educational and professional qualifications" hint="One qualification per line." required rows="4" /><x-field name="certification_status" label="Certification status" hint="For example, certified / in progress" required /><x-field name="reporting_line" label="Direct organisational reporting line" required /><x-field name="appointed_at" label="Appointment date" type="date" required /></div></div>
    <div class="grid gap-5 lg:col-span-2"><h2 class="border-b border-slate-200 pb-3 font-bold">3. Declaration</h2><x-textarea name="appointment_declaration" label="Appointment declaration" required rows="5" /></div>
    <div class="flex justify-end gap-3 border-t border-slate-200 pt-6 lg:col-span-2"><a href="{{ route('compliance.dp2.index') }}" class="button-secondary">Cancel</a><button class="button-primary" type="submit">Save appointment</button></div>
</form>
@endsection